---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-flink-shang12360-cn-v1-flinksession
  failurePolicy: Fail
  name: mflinksession.kb.io
  rules:
  - apiGroups:
    - flink.shang12360.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flinksessions
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-flink-shang12360-cn-v1-flinksession
  failurePolicy: Fail
  name: vflinksession.kb.io
  rules:
  - apiGroups:
    - flink.shang12360.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - flinksessions
  sideEffects: None
