# permissions for end users to view flinksessions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flinksession-viewer-role
rules:
- apiGroups:
  - flink.shang12360.cn
  resources:
  - flinksessions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flink.shang12360.cn
  resources:
  - flinksessions/status
  verbs:
  - get
