---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - flink.shang12360.cn
  resources:
  - flinksessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flink.shang12360.cn
  resources:
  - flinksessions/finalizers
  verbs:
  - update
- apiGroups:
  - flink.shang12360.cn
  resources:
  - flinksessions/status
  verbs:
  - get
  - patch
  - update
