name: Go

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Go Mod 
      run: go mod tidy -v 

    - name: Build
      run: make manifests generate build

    - name: Test
      run: make manifests generate test
